### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by ghost** [DevCoder1309/Leetcode_Problems#2]
python kon use karta hai bhai eww

**Comment by DevCoder1309** [comment]
😑😂

**Comment by Debajyati** [comment]
what's the issue?

**Comment by COMMANDO2406** [comment]
Why is this an issue...

**Comment by Silenwolf02** [comment]
> Why is this an issue...

Bhai ise hi insider jokes 🤣

**Comment by Silenwolf02** [comment]
> 

Lol 😆

**Comment by DevCoder1309** [comment]
there's no issue guys he was just kidding with me!! 😅

**Comment by Silenwolf02** [comment]
> Was searching for issues, this was the best one I found.

True!
 thank me for raising the issue 😉
